# Generated by Django 4.1.1 on 2022-10-17 22:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creation_datetimee', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Creation_datetimee')),
                ('Album_name', models.CharField(default='New Album', max_length=200)),
                ('Release_datetime', models.DateField()),
                ('Cost', models.FloatField(blank=True)),
                ('Is_approved', models.BooleanField(default=False, help_text=' Approve the album if its name is not explicit')),
                ('Artist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artists')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
