# Generated by Django 3.0 on 2022-10-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
