# Generated by Django 3.0 on 2022-10-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0002_delete_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artistname', models.CharField(max_length=200)),
                ('Albumname', models.CharField(max_length=200)),
                ('Creationdatetime', models.DateField(auto_now_add=True)),
                ('Releasedatetime', models.DateField()),
                ('Cost', models.FloatField(blank=True)),
            ],
        ),
    ]
