# Generated by Django 3.0 on 2022-10-21 19:34

import django.core.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])]),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='music_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(upload_to='thumbs/'),
        ),
    ]
