# Generated by Django 3.0 on 2022-10-06 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0008_auto_20221006_2139'),
        ('albums', '0003_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Albumname',
            field=models.CharField(default='New Album', max_length=200),
        ),
        migrations.AlterField(
            model_name='album',
            name='Artistname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.Artists'),
        ),
    ]
