# Generated by Django 3.0 on 2022-10-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_auto_20221006_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='Approved',
            field=models.BooleanField(default=False),
        ),
    ]
