# Generated by Django 3.0 on 2022-10-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_auto_20221006_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Creationdatetime',
            field=models.DateField(),
        ),
    ]
