# Generated by Django 3.0 on 2022-10-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_album_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Creationdatetime',
            field=models.DateField(),
        ),
    ]
