# Generated by Django 3.0 on 2022-10-17 00:56

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_auto_20221009_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='Albumname',
            new_name='Album_name',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='Artistname',
            new_name='Artist_name',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='Creationdatetime',
            new_name='Release_datetime',
        ),
        migrations.RemoveField(
            model_name='album',
            name='Releasedatetime',
        ),
        migrations.AddField(
            model_name='album',
            name='Creation_datetimee',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Creation_datetimee'),
        ),
        migrations.AddField(
            model_name='album',
            name='Is_approved',
            field=models.BooleanField(default=False, help_text=' Approve the album if its name is not explicit'),
        ),
    ]
