# Generated by Django 3.0 on 2022-10-09 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_auto_20221009_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='Creationdatetime',
            new_name='Creationdatetimee',
        ),
    ]
