# Generated by Django 3.0 on 2022-10-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_auto_20221009_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Creationdatetimee',
            field=models.DateField(editable=False),
        ),
    ]
