# Generated by Django 3.0 on 2022-10-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_auto_20221009_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='Approved',
            field=models.BooleanField(default=False),
        ),
    ]
