# Generated by Django 3.0 on 2022-10-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_album_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(help_text='Please enter your name...', max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='album',
            name='Creationdatetimee',
            field=models.DateField(),
        ),
    ]
