# Generated by Django 3.0 on 2022-10-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_auto_20221009_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='name',
        ),
        migrations.AddField(
            model_name='album',
            name='ExplicitName',
            field=models.CharField(help_text='Please enter your Approve...', max_length=300, null=True),
        ),
    ]
