# Generated by Django 3.0 on 2022-10-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_auto_20221010_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Approved',
            field=models.BooleanField(default=False, help_text='Please enter your Approve...'),
        ),
        migrations.AlterField(
            model_name='album',
            name='ExplicitName',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
