# Generated by Django 4.1.2 on 2022-10-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_auto_20221018_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
