# Generated by Django 3.0 on 2022-10-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_auto_20221006_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artists',
            old_name='link',
            new_name='Link',
        ),
        migrations.RemoveField(
            model_name='artists',
            name='name',
        ),
        migrations.AddField(
            model_name='artists',
            name='Name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
