# Generated by Django 3.0 on 2022-10-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_auto_20221006_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='Name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
