# Generated by Django 3.0 on 2022-10-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20221006_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='Name',
            field=models.CharField(max_length=200),
        ),
    ]
