# Generated by Django 3.0 on 2022-10-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_auto_20221006_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='Link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
