# Generated by Django 3.0 on 2022-10-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_auto_20221006_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='Link',
            field=models.URLField(blank=True),
        ),
    ]
