# Generated by Django 3.0 on 2022-10-15 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0008_auto_20221006_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artists',
            old_name='Link',
            new_name='Artist_link',
        ),
        migrations.RenameField(
            model_name='artists',
            old_name='Name',
            new_name='Artist_name',
        ),
    ]
